spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gggshk/spring-cloud-config-example # 설정 파일을 저장한 레포지토리 주소
          search-paths: files/** # 설정 파일을 조회할 디렉터리 경로
          default-label: main # 클라이언트가 브랜치를 따로 지정하지 않으면 해당 브랜치를 기본으로 사용
          clone-on-start: on # 서버가 시작될 때 저장소를 클론한다. 잘못된 설정(잘못된 저장소 uri 등)을 빠르게 식별할 수 있기 때문에 해당 설정을 on하는 것을 추천한다.
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
server:
  port: 8888 # 기본 포트는 8080이다.