CREATE DATABASE IF NOT EXISTS config;

use config;

CREATE TABLE IF NOT EXISTS PROPERTIES
(
    APPLICATION VARCHAR(50)   NOT NULL,
    PROFILE     VARCHAR(16)   NOT NULL DEFAULT 'default',
    LABEL       VARCHAR(16)   NOT NULL DEFAULT 'main',
    `KEY`       VARCHAR(256)  NOT NULL,
    `VALUE`     VARCHAR(1024) NOT NULL,
    PRIMARY KEY (`KEY`)
);