spring:
  application:
    name: app
  config:
    import: optional:configserver:http://localhost:8888 # optional 접두사를 제거하면 fail-fast=true 와 같다.
  cloud:
    config:
      fail-fast: true # 구성 서버 연결에 실패하면 클라이언트도 실행 실패
      retry: # 구성 서버 연결에 실패할 경우 재시도를 할 수 있다. fail-fast=true가 선행되어야 한다.
        max-attempts: 3 # 재시도 횟수
